produits:
    pattern:  /
    defaults: { _controller: EcommerceBundle:Produits:produits }

presentation:
    pattern:  /produit
    defaults: { _controller: EcommerceBundle:Produits:presentation }

panier:
    pattern:  /panier
    defaults: { _controller: EcommerceBundle:Panier:panier }

livraison:
    pattern:  /panier/livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }

validation:
    pattern:  /panier/validation
    defaults: { _controller: EcommerceBundle:Panier:validation }



test:
    pattern:  /test
    defaults: { _controller: EcommerceBundle:Test:testFormulaire }