parameters:
#    ecommerce.example.class: Ecommerce\EcommerceBundle\Example

services:
    tva:
      class: Ecommerce\EcommerceBundle\Twig\Extension\TvaExtension
      tags:
        - { name: twig.extension }
