utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /

